services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=master
      - POSTGRES_DB=mana
      - PGADMIN_DEFAULT_EMAIL=info@mana.do
      - PGADMIN_DEFAULT_PASSWORD=master
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    command: postgres -c wal_level=logical -c max_replication_slots=4 -c max_wal_senders=4

volumes:
  pgdata:
  redis_data:
  miniodata:
