/* eslint-disable */
/* tslint:disable */
// noinspection JSUnusedGlobalSymbols
// biome-ignore-all
/*
 * ------------------------------------------------------------
 * ## This file was automatically generated by drizzle-zero. ##
 * ## Any changes you make to this file will be overwritten. ##
 * ##                                                        ##
 * ## Additionally, you should also exclude this file from   ##
 * ## your linter and/or formatter to prevent it from being  ##
 * ## checked or modified.                                   ##
 * ##                                                        ##
 * ## SOURCE: https://github.com/BriefHQ/drizzle-zero        ##
 * ------------------------------------------------------------
 */

import type { ZeroCustomType } from "drizzle-zero";
import type { default as zeroSchema } from "./drizzle-zero.config";

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    media: {
      name: "media",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "media",
            "id"
          >,
        },
        alt: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "media",
            "alt"
          >,
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "media",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "media",
            "createdAt"
          >,
          serverName: "created_at",
        },
        url: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "media",
            "url"
          >,
        },
        thumbnailURL: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "media",
            "thumbnailURL"
          >,
          serverName: "thumbnail_u_r_l",
        },
        filename: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "media",
            "filename"
          >,
        },
        mimeType: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "media",
            "mimeType"
          >,
          serverName: "mime_type",
        },
        filesize: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "media",
            "filesize"
          >,
        },
        width: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "media",
            "width"
          >,
        },
        height: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "media",
            "height"
          >,
        },
        focalX: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "media",
            "focalX"
          >,
          serverName: "focal_x",
        },
        focalY: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "media",
            "focalY"
          >,
          serverName: "focal_y",
        },
      },
      primaryKey: ["id"],
    },
    payload_locked_documents: {
      name: "payload_locked_documents",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_locked_documents",
            "id"
          >,
        },
        globalSlug: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_locked_documents",
            "globalSlug"
          >,
          serverName: "global_slug",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_locked_documents",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_locked_documents",
            "createdAt"
          >,
          serverName: "created_at",
        },
      },
      primaryKey: ["id"],
    },
    payload_locked_documents_rels: {
      name: "payload_locked_documents_rels",
      columns: {
        id: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_locked_documents_rels",
            "id"
          >,
        },
        order: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_locked_documents_rels",
            "order"
          >,
        },
        parent: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_locked_documents_rels",
            "parent"
          >,
          serverName: "parent_id",
        },
        path: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_locked_documents_rels",
            "path"
          >,
        },
        usersID: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_locked_documents_rels",
            "usersID"
          >,
          serverName: "users_id",
        },
        mediaID: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_locked_documents_rels",
            "mediaID"
          >,
          serverName: "media_id",
        },
        pipelinesID: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_locked_documents_rels",
            "pipelinesID"
          >,
          serverName: "pipelines_id",
        },
        stagesID: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_locked_documents_rels",
            "stagesID"
          >,
          serverName: "stages_id",
        },
        tasksID: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_locked_documents_rels",
            "tasksID"
          >,
          serverName: "tasks_id",
        },
      },
      primaryKey: ["id"],
    },
    payload_migrations: {
      name: "payload_migrations",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_migrations",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_migrations",
            "name"
          >,
        },
        batch: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_migrations",
            "batch"
          >,
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_migrations",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_migrations",
            "createdAt"
          >,
          serverName: "created_at",
        },
      },
      primaryKey: ["id"],
    },
    payload_preferences: {
      name: "payload_preferences",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_preferences",
            "id"
          >,
        },
        key: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_preferences",
            "key"
          >,
        },
        value: {
          type: "json",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_preferences",
            "value"
          >,
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_preferences",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_preferences",
            "createdAt"
          >,
          serverName: "created_at",
        },
      },
      primaryKey: ["id"],
    },
    payload_preferences_rels: {
      name: "payload_preferences_rels",
      columns: {
        id: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_preferences_rels",
            "id"
          >,
        },
        order: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_preferences_rels",
            "order"
          >,
        },
        parent: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_preferences_rels",
            "parent"
          >,
          serverName: "parent_id",
        },
        path: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_preferences_rels",
            "path"
          >,
        },
        usersID: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "payload_preferences_rels",
            "usersID"
          >,
          serverName: "users_id",
        },
      },
      primaryKey: ["id"],
    },
    pipelines: {
      name: "pipelines",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "pipelines",
            "id"
          >,
        },
        title: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "pipelines",
            "title"
          >,
        },
        description: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "pipelines",
            "description"
          >,
        },
        backgroundColor: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "pipelines",
            "backgroundColor"
          >,
          serverName: "background_color",
        },
        owner: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "pipelines",
            "owner"
          >,
          serverName: "owner_id",
        },
        isPrivate: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "pipelines",
            "isPrivate"
          >,
          serverName: "is_private",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "pipelines",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "pipelines",
            "createdAt"
          >,
          serverName: "created_at",
        },
      },
      primaryKey: ["id"],
    },
    pipelines_rels: {
      name: "pipelines_rels",
      columns: {
        id: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "pipelines_rels",
            "id"
          >,
        },
        order: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "pipelines_rels",
            "order"
          >,
        },
        parent: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "pipelines_rels",
            "parent"
          >,
          serverName: "parent_id",
        },
        path: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "pipelines_rels",
            "path"
          >,
        },
        usersID: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "pipelines_rels",
            "usersID"
          >,
          serverName: "users_id",
        },
      },
      primaryKey: ["id"],
    },
    stages: {
      name: "stages",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "stages",
            "id"
          >,
        },
        title: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "stages",
            "title"
          >,
        },
        pipeline: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "stages",
            "pipeline"
          >,
          serverName: "pipeline_id",
        },
        position: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "stages",
            "position"
          >,
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "stages",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "stages",
            "createdAt"
          >,
          serverName: "created_at",
        },
      },
      primaryKey: ["id"],
    },
    tasks: {
      name: "tasks",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "tasks",
            "id"
          >,
        },
        title: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "tasks",
            "title"
          >,
        },
        description: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "tasks",
            "description"
          >,
        },
        stage: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "tasks",
            "stage"
          >,
          serverName: "stage_id",
        },
        position: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "tasks",
            "position"
          >,
        },
        assignee: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "tasks",
            "assignee"
          >,
          serverName: "assignee_id",
        },
        dueDate: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "tasks",
            "dueDate"
          >,
          serverName: "due_date",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "tasks",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "tasks",
            "createdAt"
          >,
          serverName: "created_at",
        },
      },
      primaryKey: ["id"],
    },
    tasks_labels: {
      name: "tasks_labels",
      columns: {
        _order: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "tasks_labels",
            "_order"
          >,
        },
        _parentID: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "tasks_labels",
            "_parentID"
          >,
          serverName: "_parent_id",
        },
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "tasks_labels",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "tasks_labels",
            "name"
          >,
        },
        color: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "tasks_labels",
            "color"
          >,
        },
      },
      primaryKey: ["id"],
    },
    tasks_rels: {
      name: "tasks_rels",
      columns: {
        id: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "tasks_rels",
            "id"
          >,
        },
        order: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "tasks_rels",
            "order"
          >,
        },
        parent: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "tasks_rels",
            "parent"
          >,
          serverName: "parent_id",
        },
        path: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "tasks_rels",
            "path"
          >,
        },
        usersID: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "tasks_rels",
            "usersID"
          >,
          serverName: "users_id",
        },
      },
      primaryKey: ["id"],
    },
    users: {
      name: "users",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "id"
          >,
        },
        username: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "username"
          >,
        },
        name: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "name"
          >,
        },
        first_name: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "first_name"
          >,
        },
        last_name: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "last_name"
          >,
        },
        position: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "position"
          >,
        },
        image: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "image"
          >,
          serverName: "image_id",
        },
        description: {
          type: "json",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "description"
          >,
        },
        mobile: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "mobile"
          >,
        },
        phone: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "phone"
          >,
        },
        gender: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "gender"
          >,
        },
        sub: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "sub"
          >,
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "createdAt"
          >,
          serverName: "created_at",
        },
        email: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "email"
          >,
        },
        resetPasswordToken: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "resetPasswordToken"
          >,
          serverName: "reset_password_token",
        },
        resetPasswordExpiration: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "resetPasswordExpiration"
          >,
          serverName: "reset_password_expiration",
        },
        salt: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "salt"
          >,
        },
        hash: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "hash"
          >,
        },
        loginAttempts: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "loginAttempts"
          >,
          serverName: "login_attempts",
        },
        lockUntil: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "lockUntil"
          >,
          serverName: "lock_until",
        },
      },
      primaryKey: ["id"],
    },
    users_roles: {
      name: "users_roles",
      columns: {
        order: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users_roles",
            "order"
          >,
        },
        parent: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users_roles",
            "parent"
          >,
          serverName: "parent_id",
        },
        value: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users_roles",
            "value"
          >,
        },
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users_roles",
            "id"
          >,
        },
      },
      primaryKey: ["id"],
    },
  },
  relationships: {
    pipelines: {
      owner: [
        {
          sourceField: ["owner"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
    },
    stages: {
      pipeline: [
        {
          sourceField: ["pipeline"],
          destField: ["id"],
          destSchema: "pipelines",
          cardinality: "one",
        },
      ],
    },
    tasks: {
      stage: [
        {
          sourceField: ["stage"],
          destField: ["id"],
          destSchema: "stages",
          cardinality: "one",
        },
      ],
      assignee: [
        {
          sourceField: ["assignee"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
    },
    users: {
      image: [
        {
          sourceField: ["image"],
          destField: ["id"],
          destSchema: "media",
          cardinality: "one",
        },
      ],
    },
  },
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
